import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Main1 from '../components/Main1'
import Makeout from '../components/Makeout'
import Morenike from '../components/Morenike'
import Newarrivals from '../components/Newarrivals'
import SpotLight from '../components/SpotLight'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Nike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nike.png" />
      </Head>
      <Header />
      {/* <Main1 />
      <Newarrivals />
      <SpotLight />
      <Makeout />
      <Morenike />
      <Footer /> */}
    </div>
  )
}
